# Generated by Django 5.2.7 on 2025-10-15 18:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AlunoProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curso', models.CharField(choices=[('ADS', 'Análise e Desenvolvimento de Sistemas'), ('LETRAS', 'Licenciatura em Letras Português e Espanhol'), ('AGROECO', 'Tecnologia em Agroecologia'), ('ELETRO', 'Tecnologia em Eletrônica Industrial'), ('GESTAO', 'Tecnologia em Gestão Desportiva e de Lazer'), ('PROC', 'Tecnologia em Processos Gerenciais'), ('TECELETRO', 'Técnicos Integrados ao Ensino Médio | Eletrônica'), ('TECINFO', 'Técnicos Integrados ao Ensino Médio | Informática'), ('TECLAZER', 'Técnicos Integrados ao Ensino Médio | Lazer'), ('TECGUIA', 'Técnicos Subsequentes ao Ensino Médio | Lazer'), ('EJAAGRO', 'PROEJA | Agroecologia'), ('EJACIA', 'PROEJA | Comércio'), ('POS', 'Especialização')], max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='aluno_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
