# Generated by Django 5.2.7 on 2025-10-15 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alunoprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alunoprofile',
            name='curso',
            field=models.CharField(choices=[('ADS', 'Análise e Desenvolvimento de Sistemas'), ('LETRAS', 'Licenciatura em Letras Português e Espanhol'), ('AGROECO', 'Tecnologia em Agroecologia'), ('ELETRO', 'Tecnologia em Eletrônica Industrial'), ('GESTAO', 'Tecnologia em Gestão Desportiva e de Lazer'), ('PROC', 'Tecnologia em Processos Gerenciais'), ('TECELETRO', 'Técnicos Integrados ao Ensino Médio | Eletrônica'), ('TECINFO', 'Técnicos Integrados ao Ensino Médio | Informática'), ('TECLAZER', 'Técnicos Integrados ao Ensino Médio | Lazer'), ('TECGUIA', 'Técnicos Subsequentes ao Ensino Médio | Guia de Turismo'), ('EJAAGRO', 'PROEJA | Agroecologia'), ('EJACIA', 'PROEJA | Comércio'), ('POS', 'Especialização')], max_length=100),
        ),
    ]
