# Generated by Django 5.2.7 on 2025-10-15 21:52

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_alunoprofile_curso'),
    ]

    operations = [
        migrations.AddField(
            model_name='alunoprofile',
            name='rfid_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
