# Generated by Django 5.2.7 on 2025-10-15 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_alunoprofile_curso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alunoprofile',
            name='rfid_token',
            field=models.CharField(blank=True, max_length=32, null=True, unique=True, verbose_name='UID do Cartão RFID'),
        ),
    ]
