# Generated by Django 5.2.7 on 2025-10-16 15:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_alunoprofile_rfid_token'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UnassignedUIDLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=32, unique=True, verbose_name='UID não atribuído')),
                ('first_seen', models.DateTimeField(auto_now_add=True, verbose_name='Visto pela primeira vez')),
                ('last_seen', models.DateTimeField(auto_now=True, verbose_name='Visto por último')),
            ],
        ),
        migrations.CreateModel(
            name='AccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Data e Hora')),
                ('uid', models.CharField(max_length=32, verbose_name='UID do Cartão')),
                ('status', models.CharField(choices=[('GRANTED', 'Acesso Concedido'), ('DENIED', 'Acesso Negado')], max_length=10, verbose_name='Status')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuário (se conhecido)')),
            ],
        ),
    ]
